require("array",array) new StdArray;
require("dialog", dialog) new StdDialog;
require("direct", direct) new StdDirect;
require("io", io) new StdIo;
require("os", os) new StdOs;
require("socket", socket) new StdSocket;
require("string", string) new StdString;
require("thread", thread) new StdThread;
require("time", time) new StdTime;
require("type", type) new StdType;